package tiket.wisata;

import java.awt.Font;
import java.awt.FontFormatException;
import java.io.IOException;
import java.sql.Connection;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

public class SignIn extends javax.swing.JFrame {
    
    Connection con = null;
    Statement st = null;
    Font fontBlack, fontDefault, fontExtraBold, fontMedium;
    
    String username;
    String password;
    String fullName;

    public SignIn() {
        try {
            this.fontBlack = Font.createFont(Font.TRUETYPE_FONT, getClass().getResourceAsStream("/Font/Montserrat_Black.ttf"));
            this.fontDefault = Font.createFont(Font.TRUETYPE_FONT, getClass().getResourceAsStream("/Font/Montserrat.ttf"));
            this.fontExtraBold = Font.createFont(Font.TRUETYPE_FONT, getClass().getResourceAsStream("/Font/Montserrat_ExtraBold.ttf"));
            this.fontMedium = Font.createFont(Font.TRUETYPE_FONT, getClass().getResourceAsStream("/Font/Montserrat_Medium.ttf"));
        } catch (FontFormatException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        setLocationRelativeTo(null);
        MySQLConnection DB = new MySQLConnection();
        DB.config();
        con = DB.con;
        st = DB.stm;
    }
    
     private void clrsscr(){
        textFieldUsername.setText("");
        passwordField.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LayoutLeft = new javax.swing.JPanel();
        labelTitle = new javax.swing.JLabel();
        labelSubtitle = new javax.swing.JLabel();
        separatorTitle = new javax.swing.JSeparator();
        labelBackground = new javax.swing.JLabel();
        LayoutRight = new javax.swing.JPanel();
        LabelTitle = new javax.swing.JLabel();
        textFieldUsername = new javax.swing.JTextField();
        separatorUsername = new javax.swing.JSeparator();
        labelUsername = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        separatorPassword = new javax.swing.JSeparator();
        labelPassword = new javax.swing.JLabel();
        btnSignIn = new javax.swing.JButton();
        labelInfoAccount = new javax.swing.JLabel();
        labelLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LayoutLeft.setPreferredSize(new java.awt.Dimension(400, 500));
        LayoutLeft.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTitle.setFont(fontExtraBold.deriveFont(36f));
        labelTitle.setForeground(new java.awt.Color(245, 245, 245));
        labelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitle.setText("MadeTick");
        LayoutLeft.add(labelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 400, 70));

        labelSubtitle.setFont(fontBlack.deriveFont(18f));
        labelSubtitle.setForeground(new java.awt.Color(204, 204, 204));
        labelSubtitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSubtitle.setText("Manji Destination Ticket");
        LayoutLeft.add(labelSubtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 400, 30));

        separatorTitle.setForeground(new java.awt.Color(255, 255, 255));
        LayoutLeft.add(separatorTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 340, 20));

        labelBackground.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/leftBackground.jpg"))); // NOI18N
        LayoutLeft.add(labelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 500));

        getContentPane().add(LayoutLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        LayoutRight.setBackground(new java.awt.Color(54, 79, 107));
        LayoutRight.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelTitle.setFont(fontMedium.deriveFont(Font.BOLD, 24f));
        LabelTitle.setForeground(new java.awt.Color(63, 193, 201));
        LabelTitle.setText("Masuk ");
        LayoutRight.add(LabelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        textFieldUsername.setBackground(new java.awt.Color(54, 79, 107));
        textFieldUsername.setFont(fontDefault.deriveFont(12f));
        textFieldUsername.setForeground(new java.awt.Color(255, 255, 255));
        textFieldUsername.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        textFieldUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldUsernameActionPerformed(evt);
            }
        });
        LayoutRight.add(textFieldUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 250, 30));

        separatorUsername.setForeground(new java.awt.Color(255, 255, 255));
        LayoutRight.add(separatorUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 250, 10));

        labelUsername.setFont(fontDefault.deriveFont(Font.BOLD, 14f));
        labelUsername.setForeground(new java.awt.Color(245, 245, 245));
        labelUsername.setText("Nama pengguna");
        LayoutRight.add(labelUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        passwordField.setBackground(new java.awt.Color(54, 79, 107));
        passwordField.setFont(fontDefault.deriveFont(12f));
        passwordField.setForeground(new java.awt.Color(255, 255, 255));
        passwordField.setBorder(null);
        LayoutRight.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 250, 30));

        separatorPassword.setForeground(new java.awt.Color(255, 255, 255));
        LayoutRight.add(separatorPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 250, -1));

        labelPassword.setFont(fontDefault.deriveFont(Font.BOLD, 14f));
        labelPassword.setForeground(new java.awt.Color(245, 245, 245));
        labelPassword.setText("Kata sandi");
        LayoutRight.add(labelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        btnSignIn.setBackground(new java.awt.Color(63, 193, 201));
        btnSignIn.setFont(fontDefault.deriveFont(12f));
        btnSignIn.setText("Masuk");
        btnSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignInActionPerformed(evt);
            }
        });
        LayoutRight.add(btnSignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 100, 30));

        labelInfoAccount.setFont(fontDefault.deriveFont(12f));
        labelInfoAccount.setForeground(new java.awt.Color(255, 255, 255));
        labelInfoAccount.setText("Tidak memiliki akun?");
        LayoutRight.add(labelInfoAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 140, 30));

        labelLogin.setFont(fontBlack.deriveFont(12f));
        labelLogin.setForeground(new java.awt.Color(255, 255, 255));
        labelLogin.setText("Daftar");
        labelLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelLoginMouseClicked(evt);
            }
        });
        LayoutRight.add(labelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 50, 30));

        getContentPane().add(LayoutRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 400, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignInActionPerformed
        username = textFieldUsername.getText();
        password = String.valueOf(passwordField.getPassword());
        
        try {
            Boolean isEmpyField = false; 
            
            if (username.isEmpty()) {
                isEmpyField = true;
                textFieldUsername.requestFocus();
            } else if(password.isEmpty()) {
                isEmpyField = true;
                passwordField.requestFocus();
            }
            
            if (!isEmpyField) {
                String sql = "SELECT * FROM tblogin WHERE username ='"+username+"' AND password ='"+password+"'";
                PreparedStatement stmt = con.prepareStatement(sql);
                ResultSet rs = stmt.executeQuery();
                if (rs.next()) {
                    if (username.equals(rs.getString("username")) && password.equals(rs.getString("password"))) {
                        if (username.contains("admin") && password.contains("admin")) {
                            dispose();
                            Admin admin = new Admin();
                            admin.setLocationRelativeTo(null);
                            admin.setVisible(true);
                        } else {
                            String sqlkode = "UPDATE `tblogin` SET `status`='true'"
                                    + "WHERE username ='"+username+"' AND password ='"+password+"'";
                                try{
                                    PreparedStatement p2 = (PreparedStatement) con.prepareStatement(sqlkode);
                                    p2.executeUpdate();
                                    p2.close();
                                }catch (SQLException ex){
                                    JOptionPane.showMessageDialog(this, "Terjadi Kesalahan" + ex.getMessage());
                                }
                            dispose();
                            Home home = new Home(username);
                            home.setLocationRelativeTo(null);
                            home.setVisible(true);
                        }
                    }
                   
                } else {
                    clrsscr();
                    JOptionPane.showMessageDialog(this, "Nama Pengguna atau Kata Sandi yang anda masukkan salah");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Inputan tidak boleh kosong");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error " + e.getMessage());
        }
    }//GEN-LAST:event_btnSignInActionPerformed

    private void labelLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelLoginMouseClicked
        dispose();
        SignUp daftar = new SignUp();
        daftar.setVisible(true);
    }//GEN-LAST:event_labelLoginMouseClicked

    private void textFieldUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldUsernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelTitle;
    private javax.swing.JPanel LayoutLeft;
    private javax.swing.JPanel LayoutRight;
    private javax.swing.JButton btnSignIn;
    private javax.swing.JLabel labelBackground;
    private javax.swing.JLabel labelInfoAccount;
    private javax.swing.JLabel labelLogin;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelSubtitle;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JLabel labelUsername;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JSeparator separatorPassword;
    private javax.swing.JSeparator separatorTitle;
    private javax.swing.JSeparator separatorUsername;
    private javax.swing.JTextField textFieldUsername;
    // End of variables declaration//GEN-END:variables
}
