package tiket.wisata;

import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.HeadlessException;
import java.io.IOException;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


public class SignUp extends javax.swing.JFrame{
    Connection con = null;
    Statement st = null;
    Font fontBlack, fontDefault, fontExtraBold, fontMedium;
    
    String username;
    String password;
    String fullName;

    public SignUp() {
        try {
            this.fontBlack = Font.createFont(Font.TRUETYPE_FONT, getClass().getResourceAsStream("/Font/Montserrat_Black.ttf"));
            this.fontDefault = Font.createFont(Font.TRUETYPE_FONT, getClass().getResourceAsStream("/Font/Montserrat.ttf"));
            this.fontExtraBold = Font.createFont(Font.TRUETYPE_FONT, getClass().getResourceAsStream("/Font/Montserrat_ExtraBold.ttf"));
            this.fontMedium = Font.createFont(Font.TRUETYPE_FONT, getClass().getResourceAsStream("/Font/Montserrat_Medium.ttf"));
        } catch (FontFormatException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        LayoutRight.setFocusable(true); // focus ke layout sebelah kanan ketika di run
        setLocationRelativeTo(null); // mengeset tampilan ketika dirun menjadi ditengah
        MySQLConnection DB = new MySQLConnection();
        DB.config();
        con = DB.con;
        st = DB.stm;
    }
    
    private void clrsscr(){
        textFieldFullName.setText("");
        textFieldUsername.setText("");
        passwordField.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LayoutLeft = new javax.swing.JPanel();
        labelTitle = new javax.swing.JLabel();
        labelSubtitle = new javax.swing.JLabel();
        separatorTitle = new javax.swing.JSeparator();
        labelBackground = new javax.swing.JLabel();
        LayoutRight = new javax.swing.JPanel();
        LabelTitle = new javax.swing.JLabel();
        labelFullName = new javax.swing.JLabel();
        textFieldFullName = new javax.swing.JTextField();
        separatorFullName = new javax.swing.JSeparator();
        labelUsername = new javax.swing.JLabel();
        textFieldUsername = new javax.swing.JTextField();
        separatorUsername = new javax.swing.JSeparator();
        labelPassword = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        separatorPassword = new javax.swing.JSeparator();
        cbAgree = new javax.swing.JCheckBox();
        btnSignUp = new javax.swing.JButton();
        labelInfoAccount = new javax.swing.JLabel();
        labelLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(57, 162, 219));
        setResizable(false);

        LayoutLeft.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTitle.setFont(fontExtraBold.deriveFont(36f));
        labelTitle.setForeground(new java.awt.Color(245, 245, 245));
        labelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitle.setText("MadeTick");
        LayoutLeft.add(labelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 400, 70));

        labelSubtitle.setFont(fontBlack.deriveFont(18f));
        labelSubtitle.setForeground(new java.awt.Color(204, 204, 204));
        labelSubtitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSubtitle.setText("Manji Destination Ticket");
        LayoutLeft.add(labelSubtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 400, 30));

        separatorTitle.setForeground(new java.awt.Color(255, 255, 255));
        LayoutLeft.add(separatorTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 340, 20));

        labelBackground.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/leftBackground.jpg"))); // NOI18N
        LayoutLeft.add(labelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 500));

        LayoutRight.setBackground(new java.awt.Color(54, 79, 107));
        LayoutRight.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelTitle.setFont(fontMedium.deriveFont(Font.BOLD, 24f));
        LabelTitle.setForeground(new java.awt.Color(63, 193, 201));
        LabelTitle.setText("Daftar");
        LayoutRight.add(LabelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        labelFullName.setFont(fontDefault.deriveFont(Font.BOLD, 14f));
        labelFullName.setForeground(new java.awt.Color(245, 245, 245));
        labelFullName.setText("Nama Lengkap");
        LayoutRight.add(labelFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        textFieldFullName.setBackground(new java.awt.Color(54, 79, 107));
        textFieldFullName.setFont(fontDefault.deriveFont(12f));
        textFieldFullName.setForeground(new java.awt.Color(255, 255, 255));
        textFieldFullName.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        LayoutRight.add(textFieldFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 250, 30));

        separatorFullName.setForeground(new java.awt.Color(255, 255, 255));
        LayoutRight.add(separatorFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 250, 10));

        labelUsername.setFont(fontDefault.deriveFont(Font.BOLD, 14f));
        labelUsername.setForeground(new java.awt.Color(245, 245, 245));
        labelUsername.setText("Nama pengguna");
        LayoutRight.add(labelUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        textFieldUsername.setBackground(new java.awt.Color(54, 79, 107));
        textFieldUsername.setFont(fontDefault.deriveFont(12f));
        textFieldUsername.setForeground(new java.awt.Color(255, 255, 255));
        textFieldUsername.setBorder(null);
        LayoutRight.add(textFieldUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 250, 30));

        separatorUsername.setForeground(new java.awt.Color(255, 255, 255));
        LayoutRight.add(separatorUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 250, -1));

        labelPassword.setFont(fontDefault.deriveFont(Font.BOLD, 14f));
        labelPassword.setForeground(new java.awt.Color(245, 245, 245));
        labelPassword.setText("Kata sandi");
        LayoutRight.add(labelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        passwordField.setBackground(new java.awt.Color(54, 79, 107));
        passwordField.setFont(fontDefault.deriveFont(12f));
        passwordField.setForeground(new java.awt.Color(255, 255, 255));
        passwordField.setBorder(null);
        LayoutRight.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 309, 250, 30));

        separatorPassword.setForeground(new java.awt.Color(255, 255, 255));
        LayoutRight.add(separatorPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 250, -1));

        cbAgree.setBackground(new java.awt.Color(54, 79, 107));
        cbAgree.setFont(fontDefault.deriveFont(12f));
        cbAgree.setForeground(new java.awt.Color(255, 255, 255));
        cbAgree.setText("Saya setuju dengan Syarat dan Ketentuan");
        cbAgree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAgreeActionPerformed(evt);
            }
        });
        LayoutRight.add(cbAgree, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        btnSignUp.setBackground(new java.awt.Color(63, 193, 201));
        btnSignUp.setFont(fontDefault.deriveFont(12f));
        btnSignUp.setText("Daftar");
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });
        LayoutRight.add(btnSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 100, 30));

        labelInfoAccount.setFont(fontDefault.deriveFont(12f));
        labelInfoAccount.setForeground(new java.awt.Color(255, 255, 255));
        labelInfoAccount.setText("Sudah memiliki akun?");
        LayoutRight.add(labelInfoAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, 140, 30));

        labelLogin.setFont(fontBlack.deriveFont(12f));
        labelLogin.setForeground(new java.awt.Color(255, 255, 255));
        labelLogin.setText("Masuk");
        labelLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelLoginMouseClicked(evt);
            }
        });
        LayoutRight.add(labelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, 50, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LayoutLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(LayoutRight, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LayoutLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(LayoutRight, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbAgreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAgreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAgreeActionPerformed

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        username = textFieldUsername.getText();
        password = String.valueOf(passwordField.getPassword());
        fullName = textFieldFullName.getText();
        
        try {
            Boolean isEmpyField = false; 
            
            if (fullName.isEmpty()) {
                isEmpyField = true;
                textFieldFullName.requestFocus();
            } else if (username.isEmpty()) {
                isEmpyField = true;
                textFieldUsername.requestFocus();
            } else if (password.isEmpty()) {
                isEmpyField = true;
                passwordField.requestFocus();
            }

            if (!isEmpyField && cbAgree.isSelected()) {
                st.executeUpdate("INSERT INTO `tblogin` VALUES ("
                       + "'" + fullName + "',"
                       + "'" + username + "',"
                       + "'" + password + "',"
                       + "'" + "true" 
                       + "')"
               );       
                   JOptionPane.showMessageDialog(null, "Akun berhasil dibuat");
                   dispose();
                   
                   Home home = new Home(username);
                   home.setVisible(true);
                   clrsscr();
            } else if (!isEmpyField) {
                JOptionPane.showMessageDialog(null, "Mohon untuk diceklis persetujuan");
            } else {
                JOptionPane.showMessageDialog(null, "Inputan tidak boleh kosong");
            }
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, "Error" + e.getMessage());
        }   
    }//GEN-LAST:event_btnSignUpActionPerformed
  
    private void labelLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelLoginMouseClicked
        dispose(); // mengakhiri JFrame yang sedang dipakai / mengakhir class yang sedang di jalankan
        SignIn login = new SignIn();
        login.setVisible(true);
    }//GEN-LAST:event_labelLoginMouseClicked

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelTitle;
    private javax.swing.JPanel LayoutLeft;
    private javax.swing.JPanel LayoutRight;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JCheckBox cbAgree;
    private javax.swing.JLabel labelBackground;
    private javax.swing.JLabel labelFullName;
    private javax.swing.JLabel labelInfoAccount;
    private javax.swing.JLabel labelLogin;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelSubtitle;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JLabel labelUsername;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JSeparator separatorFullName;
    private javax.swing.JSeparator separatorPassword;
    private javax.swing.JSeparator separatorTitle;
    private javax.swing.JSeparator separatorUsername;
    private javax.swing.JTextField textFieldFullName;
    private javax.swing.JTextField textFieldUsername;
    // End of variables declaration//GEN-END:variables

}
